# Generated by Django 4.1.7 on 2023-04-28 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempmodel',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 4, 28, 13, 48, 56, 386789, tzinfo=datetime.timezone.utc), verbose_name='date'),
            preserve_default=False,
        ),
    ]
